runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  # Serve pre-existing static assets (not uploads)
  - url: /static
    static_dir: static  # Your CSS/JS/images

  # Serve uploaded files via Flask route (not static)
  - url: /uploads
    static_dir: tmp/uploads  # Not recommended (use the Flask route instead)

  # All other routes
  - url: /.*
    script: auto